version: '3'
services:
  knowledgedb:
     image: mysql:5.6
     volumes:
        - "./.data/db:/var/lib/mysql"
     container_name: mysql
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=knowledgedb
        - MYSQL_USER=atm
        - MYSQL_PASSWORD=root
     ports:
         42333:3306
        
  web:
    image: atm/analyzer
    build: .
    depends_on:
       - knowledgedb
    container_name: analyzer
    restart: always
    ports:
      - "8080:8080"
      
  dashboard:
    image: nginx
    build: dashboard/
    container_name: dashboard
    restart: always
    ports:
      - "80:80"