version: '3'
services:
  web:
    image: atm/analyzer
    build: .
    container_name: analyzer
    restart: always
    ports:
      - "8080:8080"
  dashboard:
    image: eubraatmosphere/tma-dashboard:2.0
    build: dashboard/
    container_name: dashboard
    restart: always
    ports:
      - "80:80"
      - "3000:3000"